apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}-nodeport
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPortName }}
      protocol: TCP
      name: {{ .Values.service.name }}
      nodePort: 30092
  selector:
    {{- include "mlflow.selectorLabels" . | nindent 4 }}
