apiVersion: v1
kind: Service
metadata:
  name: {{ include "woodpecker-server.fullname" . }}-local
  labels:
    {{- include "woodpecker-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceLocal.type }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.serviceLocal.port }}
      targetPort: {{ .Values.serviceLocal.targetPort }}
      nodePort: {{ .Values.serviceLocal.nodePort }}

  selector:
    {{- include "woodpecker-server.selectorLabels" . | nindent 4 }}
